import {
  ArrowRightLeft,
  BadgeDollarSign,
  BriefcaseBusiness,
  Building2,
  CircleDollarSign,
  CreditCard,
  FileClock,
  FileText,
  LayoutDashboard,
  MessagesSquare,
  Receipt,
  Scale,
  Send,
  Settings2,
  Sparkles,
  Users,
  Wallet,
} from 'lucide-react';

import type { GlobalSearchResultPayload, GlobalSearchScope } from './types';

export const demoScopes: GlobalSearchScope[] = [
  {
    id: 'payments',
    label: 'Payments',
    description: 'Move money, review payouts, and initiate transfers.',
    icon: ArrowRightLeft,
    keywords: ['transfer', 'send', 'money', 'pay'],
  },
  {
    id: 'accounts',
    label: 'Accounts',
    description: 'Inspect balances, statements, and linked bank accounts.',
    icon: Building2,
    keywords: ['bank', 'wallet', 'balance'],
  },
  {
    id: 'budgets',
    label: 'Budgets',
    description: 'Track limits, approvals, and department budgets.',
    icon: BriefcaseBusiness,
    keywords: ['limit', 'department', 'approval'],
  },
  {
    id: 'requests',
    label: 'Requests',
    description: 'Search reimbursement, cash, and card funding requests.',
    icon: Receipt,
    keywords: ['approval', 'reimbursement', 'request'],
  },
  {
    id: 'menu',
    label: 'Menu',
    description: 'Navigate the product and jump between dashboard sections.',
    icon: LayoutDashboard,
    keywords: ['navigation', 'pages', 'sidebar'],
  },
];

export const demoSearchData: GlobalSearchResultPayload = {
  featuredScopeIds: ['payments', 'accounts', 'budgets', 'requests'],
  actions: [
    {
      id: 'ask-ai',
      title: 'Ask Bujeti AI',
      description: 'Use AI to answer product and finance questions instantly.',
      icon: Sparkles,
      shortcut: 'mod+q',
      keywords: ['chat', 'assistant', 'help', 'question'],
      pinned: true,
      accent: true,
    },
    {
      id: 'request-funds',
      title: 'Request funds',
      description: 'Create a new funding request for a teammate or vendor.',
      icon: FileClock,
      scopeId: 'requests',
      shortcut: 'mod+r',
      keywords: ['money', 'cash', 'advance'],
      pinned: true,
    },
    {
      id: 'create-card',
      title: 'Create a card',
      description: 'Spin up a virtual card for subscriptions or team spend.',
      icon: CreditCard,
      scopeId: 'payments',
      shortcut: 'mod+d',
      keywords: ['virtual card', 'card', 'spend'],
      pinned: true,
    },
    {
      id: 'add-account',
      title: 'Add an account',
      description: 'Link a new bank account or wallet to the workspace.',
      icon: Building2,
      scopeId: 'accounts',
      shortcut: 'mod+a',
      keywords: ['bank', 'connect', 'wallet'],
      pinned: true,
    },
    {
      id: 'send-funds',
      title: 'Send funds',
      description: 'Move money to an employee, vendor, or external bank.',
      icon: Send,
      scopeId: 'accounts',
      shortcut: 'mod+s',
      keywords: ['transfer', 'payment', 'payout'],
    },
    {
      id: 'generate-statement',
      title: 'Generate statement',
      description: 'Create a downloadable statement for the selected account.',
      icon: FileText,
      scopeId: 'accounts',
      shortcut: 'mod+g',
      keywords: ['pdf', 'statement', 'download'],
    },
    {
      id: 'make-payment',
      title: 'Make a payment',
      description: 'Pay a bill, invoice, or one-off vendor expense.',
      icon: BadgeDollarSign,
      scopeId: 'payments',
      shortcut: 'mod+p',
      keywords: ['bill', 'invoice', 'pay'],
    },
    {
      id: 'view-pending-requests',
      title: 'View pending requests',
      description: 'Jump straight to requests that still need attention.',
      icon: Receipt,
      scopeId: 'requests',
      shortcut: 'shift+mod+r',
      keywords: ['approval', 'queue', 'pending'],
    },
  ],
  menuItems: [
    {
      id: 'menu-dashboard',
      label: 'Dashboard',
      description: 'Overview of balances, active budgets, and approvals.',
      icon: LayoutDashboard,
      scopeId: 'menu',
      keywords: ['overview', 'home'],
    },
    {
      id: 'menu-requests',
      label: 'Requests',
      description: 'Browse all team funding and reimbursement requests.',
      icon: Receipt,
      scopeId: 'requests',
      keywords: ['funding', 'reimbursement'],
    },
    {
      id: 'menu-transactions',
      label: 'Transactions',
      description: 'See card swipes, transfers, and settlements.',
      icon: ArrowRightLeft,
      scopeId: 'payments',
      keywords: ['ledger', 'history', 'activity'],
    },
    {
      id: 'menu-accounts',
      label: 'Accounts',
      description: 'Inspect banks, wallets, and available balances.',
      icon: Building2,
      scopeId: 'accounts',
      keywords: ['bank', 'wallet', 'balance'],
    },
    {
      id: 'menu-budgets',
      label: 'Budgets',
      description: 'Review live spend versus departmental limits.',
      icon: BriefcaseBusiness,
      scopeId: 'budgets',
      keywords: ['department', 'limits'],
    },
    {
      id: 'menu-cards',
      label: 'Cards',
      description: 'Manage virtual cards and card controls.',
      icon: CreditCard,
      scopeId: 'payments',
      keywords: ['virtual', 'controls', 'freeze'],
    },
    {
      id: 'menu-invoices',
      label: 'Invoices',
      description: 'Track invoice status and aging at a glance.',
      icon: FileText,
      scopeId: 'payments',
      keywords: ['invoice', 'aging'],
    },
    {
      id: 'menu-compliance',
      label: 'Compliance',
      description: 'Stay on top of approvals, policy, and exceptions.',
      icon: Scale,
      scopeId: 'budgets',
      keywords: ['policy', 'approval'],
    },
    {
      id: 'menu-team',
      label: 'Team management',
      description: 'Invite members, adjust roles, and review activity.',
      icon: Users,
      scopeId: 'menu',
      keywords: ['users', 'members', 'roles'],
    },
    {
      id: 'menu-settings',
      label: 'Settings',
      description: 'Control workspace defaults, notifications, and billing.',
      icon: Settings2,
      scopeId: 'menu',
      keywords: ['preferences', 'workspace'],
    },
  ],
  records: [
    {
      id: 'req-adewale-akande',
      title: 'Adewale Akande',
      description: 'Product design sprint reimbursement',
      scopeId: 'requests',
      entity: 'Request',
      amount: 'N210,000.00',
      timestamp: '5 mins ago',
      avatarFallback: 'A',
      status: { label: 'Pending', tone: 'amber' },
      tags: ['Request', 'Top up'],
      keywords: ['adewale', 'design', 'reimbursement'],
    },
    {
      id: 'req-zulijjah-courtyard',
      title: 'Zulijjah Courtyard',
      description: 'Venue payment for leadership offsite',
      scopeId: 'requests',
      entity: 'Vendor',
      amount: 'N1,430,000.00',
      timestamp: 'Today',
      avatarFallback: 'Z',
      status: { label: 'Paid', tone: 'green' },
      tags: ['Request', 'Top up'],
      keywords: ['venue', 'vendor', 'offsite'],
    },
    {
      id: 'req-bodija-jackson',
      title: 'Bodija Jackson',
      description: 'Team lunch repayment',
      scopeId: 'requests',
      entity: 'Payment',
      amount: 'N600.00',
      timestamp: 'Today',
      avatarFallback: 'B',
      status: { label: 'Declined', tone: 'red' },
      tags: ['Request', 'Payment'],
      keywords: ['lunch', 'meal'],
    },
    {
      id: 'acct-gtbank',
      title: 'GTBank operations account',
      description: 'Primary treasury account for naira settlements',
      scopeId: 'accounts',
      entity: 'Account',
      amount: 'N57,000,000.00',
      timestamp: 'Updated 3 mins ago',
      icon: Wallet,
      status: { label: 'Healthy', tone: 'green' },
      tags: ['Bank account'],
      keywords: ['gtbank', 'operations', 'treasury'],
    },
    {
      id: 'acct-wallet',
      title: 'USD wallet',
      description: 'Collection wallet for partner payouts',
      scopeId: 'accounts',
      entity: 'Wallet',
      amount: '$128,430.22',
      timestamp: 'Updated now',
      icon: CircleDollarSign,
      status: { label: 'Live', tone: 'blue' },
      tags: ['Wallet'],
      keywords: ['usd', 'foreign', 'wallet'],
    },
    {
      id: 'budget-marketing',
      title: 'Marketing budget',
      description: 'Q2 paid media, content, and events budget',
      scopeId: 'budgets',
      entity: 'Budget',
      amount: '82% utilized',
      timestamp: 'Closes in 9 days',
      icon: BriefcaseBusiness,
      status: { label: 'Watchlist', tone: 'amber' },
      tags: ['Department'],
      keywords: ['marketing', 'paid media', 'content'],
    },
    {
      id: 'budget-people',
      title: 'People operations budget',
      description: 'Hiring, wellness, and onboarding budget',
      scopeId: 'budgets',
      entity: 'Budget',
      amount: '41% utilized',
      timestamp: 'Closes in 16 days',
      icon: BriefcaseBusiness,
      status: { label: 'On track', tone: 'green' },
      tags: ['Department'],
      keywords: ['hr', 'people', 'onboarding'],
    },
    {
      id: 'pay-invoice-2191',
      title: 'Invoice INV-2191',
      description: 'Media buying invoice from Echo Studio',
      scopeId: 'payments',
      entity: 'Invoice',
      amount: 'N3,200,000.00',
      timestamp: 'Due tomorrow',
      icon: FileText,
      status: { label: 'Due soon', tone: 'amber' },
      tags: ['Invoice'],
      keywords: ['echo studio', 'invoice', 'media'],
    },
    {
      id: 'pay-runway',
      title: 'March burn rate',
      description: 'Dashboard metric rendered on the finance home view',
      scopeId: 'payments',
      entity: 'Insight',
      amount: 'N24.8M',
      timestamp: 'Updated today',
      icon: BadgeDollarSign,
      status: { label: 'Down 8%', tone: 'green' },
      tags: ['Dashboard metric'],
      keywords: ['burn rate', 'dashboard', 'metric'],
    },
    {
      id: 'pay-assistant',
      title: 'Collections assistant',
      description: 'AI helper for vendor follow-ups and reconciliation',
      scopeId: 'menu',
      entity: 'Assistant',
      icon: MessagesSquare,
      timestamp: 'Shortcut available',
      status: { label: 'Ready', tone: 'blue' },
      tags: ['AI'],
      keywords: ['assistant', 'chat', 'ai'],
    },
  ],
  recentSearches: [
    {
      id: 'recent-last-payment',
      label: 'Last payment to Adewale',
      description: 'Jump back into the latest outgoing payment activity.',
      query: 'Adewale payment',
      scopeId: 'payments',
      timestamp: '5 mins ago',
    },
    {
      id: 'recent-invoice-600',
      label: '600,000 in invoices',
      description: 'Review invoices matching the latest amount filter.',
      query: '600000 invoices',
      scopeId: 'payments',
      timestamp: 'Yesterday',
    },
    {
      id: 'recent-fund-requests',
      label: 'Fund requests last 30 days',
      description: 'Look through the last month of team funding requests.',
      query: 'fund requests last 30 days',
      scopeId: 'requests',
      timestamp: '4 days ago',
    },
    {
      id: 'recent-gtbank',
      label: 'GTBank account',
      description: 'Reopen treasury account balances and details.',
      query: 'GTBank account',
      scopeId: 'accounts',
      timestamp: '7 days ago',
    },
    {
      id: 'recent-card-balance',
      label: 'Verve card balance',
      description: 'Inspect card funds and related transaction history.',
      query: 'Verve card balance',
      scopeId: 'payments',
      timestamp: '24 April',
    },
  ],
};
